export const THROW_ERROR_IN_COMPONENTS = 'THROW_ERROR_IN_COMPONENTS'
export const THROW_ERROR_IN_REDUCERS = 'THROW_ERROR_IN_REDUCERS'
export const THROW_ERROR_IN_SAGAS = 'THROW_ERROR_IN_SAGAS'
export const THROW_ERROR_IN_SELECTORS = 'THROW_ERROR_IN_SELECTORS'

export const API_GET = 'API_GET'
export const API_GET_SUCCESS = 'API_GET_SUCCESS'
export const API_GET_FAILURE = 'API_GET_FAILURE'
